// ═══════════════════════════════════════════════════════════════
// Auto-generated by NyxCode Backend Compiler
// Do not edit — regenerate from your .nyx source
// ═══════════════════════════════════════════════════════════════

const express = require('express');
const path = require('path');
const Database = require('better-sqlite3');
const rateLimit = require('express-rate-limit');

const app = express();


app.set("trust proxy", 1);
app.use(express.json());





const writeLimiter = rateLimit({ windowMs: 15 * 60 * 1000, max: 100, message: { error: 'Too many requests' } });

const db = new Database(process.env.DB_PATH || 'app.db');
db.pragma('journal_mode = WAL');
db.pragma('foreign_keys = ON');


// ── Auth (bcryptjs + jsonwebtoken + rate-limit) ─────────────────────
const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');
// rateLimit already declared by backend compiler
const authLimiter = rateLimit({ windowMs: 15 * 60 * 1000, max: 20, message: { error: 'Too many attempts, try again later' } });
app.use('/api/auth', authLimiter);

const JWT_SECRET = process.env.JWT_SECRET || (process.env.NODE_ENV === 'production' ? (() => { console.error('❌ FATAL: JWT_SECRET not set in production!'); process.exit(1); })() : 'nyx-dev-' + require('crypto').randomBytes(8).toString('hex'));
if (!process.env.JWT_SECRET && process.env.NODE_ENV !== 'production') console.warn('⚠️  No JWT_SECRET set — using random dev secret (tokens expire on restart)');


// Register
app.post('/api/auth/register', (req, res) => {
  const { email, password, org_name, plan } = req.body;
  if (!email || !password) return res.status(400).json({ error: 'email and password required' });
  if (!req.body.email && req.body.email !== 0) return res.status(400).json({ error: 'email is required' });
  if (!req.body.password && req.body.password !== 0) return res.status(400).json({ error: 'password is required' });
  const hash = bcrypt.hashSync(password, 10);
  try {
    const result = db.prepare('INSERT INTO users (email, password, org_name, plan) VALUES (?, ?, ?, ?)').run(email, hash, org_name, plan);
    const token = jwt.sign({ id: result.lastInsertRowid, email }, JWT_SECRET, { expiresIn: '7d' });
    res.json({ token, user: { id: result.lastInsertRowid, email } });
  } catch(e) {
    res.status(409).json({ error: 'User already exists' });
  }
});

// Login
app.post('/api/auth/login', (req, res) => {
  const { email, password } = req.body;
  if (!email || !password) return res.status(400).json({ error: 'email and password required' });
  const user = db.prepare('SELECT * FROM users WHERE email = ?').get(email);
  if (!user || !bcrypt.compareSync(password, user.password)) {
    return res.status(401).json({ error: 'Invalid credentials' });
  }
  const token = jwt.sign({ id: user.id, email: user.email }, JWT_SECRET, { expiresIn: '7d' });
  res.json({ token, user: { id: user.id, email: user.email } });
});

// Auth middleware
function authMiddleware(req, res, next) {
  const auth = req.headers.authorization;
  if (!auth?.startsWith('Bearer ')) return res.status(401).json({ error: 'No token provided' });
  try {
    req.user = jwt.verify(auth.slice(7), JWT_SECRET);
    next();
  } catch(e) {
    res.status(401).json({ error: 'Invalid or expired token' });
  }
}

// Me endpoint
app.get('/api/auth/me', authMiddleware, (req, res) => {
  const user = db.prepare('SELECT * FROM users WHERE id = ?').get(req.user.id);
  if (!user) return res.status(404).json({ error: 'User not found' });
  const { password: _, ...safe } = user;
  res.json(safe);
});

// Protect /api/monitors (all methods)
app.use('/api/monitors', (req, res, next) => { if (req.method === 'GET') return next(); return authMiddleware(req, res, next); });

// Protect /api/incidents (write only)
app.use('/api/incidents', (req, res, next) => { if (req.method !== 'GET') return authMiddleware(req, res, next); next(); });

// Protect /api/status-pages (write only)
app.use('/api/status-pages', (req, res, next) => { if (req.method !== 'GET') return authMiddleware(req, res, next); next(); });

// Protect /api/checks (all methods)
app.use('/api/checks', authMiddleware);

// ── Create tables ──────────────────────────────────────────────

db.exec(`CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    email TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    org_name TEXT DEFAULT 'My Org',
    plan TEXT DEFAULT 'hobby'
  )`);
db.exec(`CREATE TABLE IF NOT EXISTS monitors (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    url TEXT NOT NULL,
    type TEXT DEFAULT 'https',
    interval_seconds INTEGER DEFAULT '60',
    status TEXT DEFAULT 'unknown',
    last_check DATETIME DEFAULT CURRENT_TIMESTAMP,
    avg_response_ms INTEGER DEFAULT '0',
    uptime_30d INTEGER DEFAULT '100',
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
  )`);
db.exec(`CREATE TABLE IF NOT EXISTS alerts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    monitor_id INTEGER REFERENCES monitors(id) ON DELETE CASCADE,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    type TEXT DEFAULT 'email',
    target TEXT,
    enabled TEXT DEFAULT '1',
    created_at TEXT DEFAULT 'now'
  )`);
db.exec(`CREATE TABLE IF NOT EXISTS checks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    monitor_id INTEGER REFERENCES monitors(id) ON DELETE CASCADE,
    status TEXT,
    response_ms INTEGER,
    status_code INTEGER,
    error_msg TEXT,
    created_at TEXT DEFAULT 'now'
  )`);
db.exec(`CREATE TABLE IF NOT EXISTS incidents (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    status TEXT DEFAULT 'investigating',
    message TEXT,
    resolved_at TEXT,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
  )`);
db.exec(`CREATE TABLE IF NOT EXISTS incident_updates (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    incident_id INTEGER REFERENCES incidents(id) ON DELETE CASCADE,
    status TEXT,
    message TEXT NOT NULL
  )`);
db.exec(`CREATE TABLE IF NOT EXISTS status_pages (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    slug TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    monitor_ids TEXT,
    custom_domain TEXT,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
  )`);

// ── users CRUD ──────────────────────────────────────

app.get('/api/users', (req, res) => {
  // ── Filtering & Search ──
  const validColumns = new Set(["email","password","org_name","plan"]);
  const textColumns = ["email","password","org_name","plan"];
  const filters = [];
  const params = [];
  for (const [key, value] of Object.entries(req.query)) {
    if (key === 'page' || key === 'limit' || key === 'search') continue;
    if (validColumns.has(key)) {
      filters.push(key + ' = ?');
      params.push(value);
    }
  }
  if (req.query.search && textColumns.length > 0) {
    filters.push('(' + textColumns.map(c => c + ' LIKE ?').join(' OR ') + ')');
    textColumns.forEach(() => params.push('%' + req.query.search + '%'));
  }
  const where = filters.length > 0 ? ' WHERE ' + filters.join(' AND ') : '';

  // ── Pagination (opt-in: only when ?page= or ?limit= is provided) ──
  if (req.query.page || req.query.limit) {
    const page = Math.max(1, parseInt(req.query.page) || 1);
    const limit = Math.min(100, Math.max(1, parseInt(req.query.limit) || 20));
    const offset = (page - 1) * limit;
    const total = db.prepare('SELECT COUNT(*) as count FROM users' + where).get(...params).count;
    const rows = db.prepare('SELECT * FROM users' + where + ' LIMIT ? OFFSET ?').all(...params, limit, offset).map(({ password: _, ...r }) => r);
    return res.json({ data: rows, pagination: { page, limit, total, pages: Math.ceil(total / limit) } });
  }

  // ── Default: return plain array (backwards-compatible) ──
  const rows = db.prepare('SELECT * FROM users' + where).all(...params).map(({ password: _, ...r }) => r);
  res.json(rows);
});

app.get('/api/users/:id', (req, res) => {
  const row = db.prepare('SELECT * FROM users WHERE id = ?').get(req.params.id);
  if (!row) return res.status(404).json({ error: 'Not found' });
  if (row.password) { const { password: _, ...safe } = row; return res.json(safe); }
  res.json(row);
});

app.post('/api/users', writeLimiter, (req, res) => {
  try {
    if (!req.body.email && req.body.email !== 0) return res.status(400).json({ error: 'email is required' });
    if (!req.body.password && req.body.password !== 0) return res.status(400).json({ error: 'password is required' });
    const { email, password, org_name, plan } = req.body;

    const info = db.prepare(
      'INSERT INTO users (email, password, org_name, plan) VALUES (?, ?, ?, ?)'
    ).run(email, password, org_name, plan);
    res.status(201).json(db.prepare('SELECT * FROM users WHERE id = ?').get(info.lastInsertRowid));
  } catch (e) {
    res.status(400).json({ error: e.message });
  }
});

app.put('/api/users/:id', writeLimiter, (req, res) => {
  try {
  const validCols = new Set(["email","password","org_name","plan"]);
  const fields = Object.keys(req.body).filter(k => k !== 'id' && validCols.has(k));
  if (!fields.length) return res.status(400).json({ error: 'No valid fields to update' });
  const sets = fields.map(f => f + ' = ?').join(', ');
  const vals = fields.map(f => req.body[f]);
  vals.push(req.params.id);
  const info = db.prepare('UPDATE users SET ' + sets + ' WHERE id = ?').run(...vals);
  if (!info.changes) return res.status(404).json({ error: 'Not found' });
  res.json(db.prepare('SELECT * FROM users WHERE id = ?').get(req.params.id));
  } catch (e) {
    res.status(400).json({ error: e.message });
  }
});

app.delete('/api/users/:id', writeLimiter, (req, res) => {
  const deleteAll = db.transaction(() => {
    db.pragma('defer_foreign_keys = ON');
    db.prepare('DELETE FROM monitors WHERE user_id = ?').run(req.params.id);
    db.prepare('DELETE FROM alerts WHERE user_id = ?').run(req.params.id);
    db.prepare('DELETE FROM incidents WHERE user_id = ?').run(req.params.id);
    db.prepare('DELETE FROM status_pages WHERE user_id = ?').run(req.params.id);
    db.prepare('DELETE FROM users WHERE id = ?').run(req.params.id);
  });
  deleteAll();
  res.json({ deleted: true });

});

// ── monitors CRUD ──────────────────────────────────────

function mapRow_monitors(row) {
    const r = { ...row };
    r.user_id = row.__user_id_id ? { id: row.__user_id_id, email: row.__user_id_email, org_name: row.__user_id_org_name, plan: row.__user_id_plan } : null;
    Object.keys(r).forEach(k => { if (k.startsWith('__')) delete r[k]; });
    return r;
  }
app.get('/api/monitors', (req, res) => {
  // ── Filtering & Search ──
  const validColumns = new Set(["name","url","type","interval_seconds","status","last_check","avg_response_ms","uptime_30d","user_id"]);
  const textColumns = ["name","url","type","status"];
  const filters = [];
  const params = [];
  for (const [key, value] of Object.entries(req.query)) {
    if (key === 'page' || key === 'limit' || key === 'search') continue;
    if (validColumns.has(key)) {
      filters.push(key + ' = ?');
      params.push(value);
    }
  }
  if (req.query.search && textColumns.length > 0) {
    filters.push('(' + textColumns.map(c => c + ' LIKE ?').join(' OR ') + ')');
    textColumns.forEach(() => params.push('%' + req.query.search + '%'));
  }
  const where = filters.length > 0 ? ' WHERE ' + filters.join(' AND ') : '';

  // ── Pagination (opt-in: only when ?page= or ?limit= is provided) ──
  if (req.query.page || req.query.limit) {
    const page = Math.max(1, parseInt(req.query.page) || 1);
    const limit = Math.min(100, Math.max(1, parseInt(req.query.limit) || 20));
    const offset = (page - 1) * limit;
    const total = db.prepare('SELECT COUNT(*) as count FROM monitors' + where).get(...params).count;
    const rows = db.prepare('SELECT * FROM monitors' + where + ' LIMIT ? OFFSET ?').all(...params, limit, offset).map(mapRow_monitors);
    return res.json({ data: rows, pagination: { page, limit, total, pages: Math.ceil(total / limit) } });
  }

  // ── Default: return plain array (backwards-compatible) ──
  const rows = db.prepare('SELECT * FROM monitors' + where).all(...params).map(mapRow_monitors);
  res.json(rows);
});


app.get('/api/monitors/mine', authMiddleware, (req, res) => {
  try {
    const rows = db.prepare(`SELECT * FROM monitors WHERE user_id = ? ORDER BY id DESC`).all(req.user.id);
    res.json(rows);
  } catch (e) {
    res.status(500).json({ error: e.message });
  }
});

app.get('/api/monitors/:id', (req, res) => {
  const row = db.prepare('SELECT monitors.id, monitors.name, monitors.url, monitors.type, monitors.interval_seconds, monitors.status, monitors.last_check, monitors.avg_response_ms, monitors.uptime_30d, monitors.user_id, users.id AS __user_id_id, users.email AS __user_id_email, users.org_name AS __user_id_org_name, users.plan AS __user_id_plan FROM monitors LEFT JOIN users ON monitors.user_id = users.id WHERE monitors.id = ?').get(req.params.id);
  if (!row) return res.status(404).json({ error: 'Not found' });
  res.json(mapRow_monitors(row));
});

app.post('/api/monitors', authMiddleware, writeLimiter, (req, res) => {
  try {
    if (!req.body.name && req.body.name !== 0) return res.status(400).json({ error: 'name is required' });
    if (!req.body.url && req.body.url !== 0) return res.status(400).json({ error: 'url is required' });
    const { name, url, type, interval_seconds, status, avg_response_ms, uptime_30d } = req.body;

    const user_id = req.user ? req.user.id : req.body.user_id;
    const info = db.prepare(
      'INSERT INTO monitors (name, url, type, interval_seconds, status, avg_response_ms, uptime_30d, user_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'
    ).run(name, url, type, interval_seconds, status, avg_response_ms, uptime_30d, user_id);
    const created = db.prepare('SELECT monitors.id, monitors.name, monitors.url, monitors.type, monitors.interval_seconds, monitors.status, monitors.last_check, monitors.avg_response_ms, monitors.uptime_30d, monitors.user_id, users.id AS __user_id_id, users.email AS __user_id_email, users.org_name AS __user_id_org_name, users.plan AS __user_id_plan FROM monitors LEFT JOIN users ON monitors.user_id = users.id WHERE monitors.id = ?').get(info.lastInsertRowid);
    
    res.status(201).json(mapRow_monitors(created));
  } catch (e) {
    res.status(400).json({ error: e.message });
  }
});

app.put('/api/monitors/:id', writeLimiter, (req, res) => {
  try {
  const validCols = new Set(["name","url","type","interval_seconds","status","avg_response_ms","uptime_30d","user_id"]);
  const fields = Object.keys(req.body).filter(k => k !== 'id' && validCols.has(k));
  if (!fields.length) return res.status(400).json({ error: 'No valid fields to update' });
  const sets = fields.map(f => f + ' = ?').join(', ');
  const vals = fields.map(f => req.body[f]);
  vals.push(req.params.id);
  const info = db.prepare('UPDATE monitors SET ' + sets + ' WHERE id = ?').run(...vals);
  if (!info.changes) return res.status(404).json({ error: 'Not found' });
  res.json(db.prepare('SELECT * FROM monitors WHERE id = ?').get(req.params.id));
  } catch (e) {
    res.status(400).json({ error: e.message });
  }
});

app.delete('/api/monitors/:id', authMiddleware, writeLimiter, (req, res) => {
  const monitor = db.prepare('SELECT user_id FROM monitors WHERE id = ?').get(req.params.id);
  if (!monitor) return res.status(404).json({ error: 'Monitor not found' });
  if (monitor.user_id !== req.user.id) return res.status(403).json({ error: 'Not your monitor' });
  const deleteAll = db.transaction(() => {
    db.pragma('defer_foreign_keys = ON');
    db.prepare('DELETE FROM alerts WHERE monitor_id = ?').run(req.params.id);
    db.prepare('DELETE FROM checks WHERE monitor_id = ?').run(req.params.id);
    db.prepare('DELETE FROM monitors WHERE id = ?').run(req.params.id);
  });
  deleteAll();
  res.json({ deleted: true });

});

// ── alerts CRUD ──────────────────────────────────────

function mapRow_alerts(row) {
    const r = { ...row };
    r.monitor_id = row.__monitor_id_id ? { id: row.__monitor_id_id, name: row.__monitor_id_name, url: row.__monitor_id_url, type: row.__monitor_id_type, interval_seconds: row.__monitor_id_interval_seconds, status: row.__monitor_id_status, last_check: row.__monitor_id_last_check, avg_response_ms: row.__monitor_id_avg_response_ms, uptime_30d: row.__monitor_id_uptime_30d, user_id: row.__monitor_id_user_id } : null;
    r.user_id = row.__user_id_id ? { id: row.__user_id_id, email: row.__user_id_email, org_name: row.__user_id_org_name, plan: row.__user_id_plan } : null;
    Object.keys(r).forEach(k => { if (k.startsWith('__')) delete r[k]; });
    return r;
  }
app.get('/api/alerts', (req, res) => {
  // ── Filtering & Search ──
  const validColumns = new Set(["monitor_id","user_id","type","target","enabled","created_at"]);
  const textColumns = ["type","target"];
  const filters = [];
  const params = [];
  for (const [key, value] of Object.entries(req.query)) {
    if (key === 'page' || key === 'limit' || key === 'search') continue;
    if (validColumns.has(key)) {
      filters.push(key + ' = ?');
      params.push(value);
    }
  }
  if (req.query.search && textColumns.length > 0) {
    filters.push('(' + textColumns.map(c => c + ' LIKE ?').join(' OR ') + ')');
    textColumns.forEach(() => params.push('%' + req.query.search + '%'));
  }
  const where = filters.length > 0 ? ' WHERE ' + filters.join(' AND ') : '';

  // ── Pagination (opt-in: only when ?page= or ?limit= is provided) ──
  if (req.query.page || req.query.limit) {
    const page = Math.max(1, parseInt(req.query.page) || 1);
    const limit = Math.min(100, Math.max(1, parseInt(req.query.limit) || 20));
    const offset = (page - 1) * limit;
    const total = db.prepare('SELECT COUNT(*) as count FROM alerts' + where).get(...params).count;
    const rows = db.prepare('SELECT * FROM alerts' + where + ' LIMIT ? OFFSET ?').all(...params, limit, offset).map(mapRow_alerts);
    return res.json({ data: rows, pagination: { page, limit, total, pages: Math.ceil(total / limit) } });
  }

  // ── Default: return plain array (backwards-compatible) ──
  const rows = db.prepare('SELECT * FROM alerts' + where).all(...params).map(mapRow_alerts);
  res.json(rows);
});

app.get('/api/alerts/:id', (req, res) => {
  const row = db.prepare('SELECT alerts.id, alerts.monitor_id, alerts.user_id, alerts.type, alerts.target, alerts.enabled, alerts.created_at, monitors.id AS __monitor_id_id, monitors.name AS __monitor_id_name, monitors.url AS __monitor_id_url, monitors.type AS __monitor_id_type, monitors.interval_seconds AS __monitor_id_interval_seconds, monitors.status AS __monitor_id_status, monitors.last_check AS __monitor_id_last_check, monitors.avg_response_ms AS __monitor_id_avg_response_ms, monitors.uptime_30d AS __monitor_id_uptime_30d, monitors.user_id AS __monitor_id_user_id, users.id AS __user_id_id, users.email AS __user_id_email, users.org_name AS __user_id_org_name, users.plan AS __user_id_plan FROM alerts LEFT JOIN monitors ON alerts.monitor_id = monitors.id LEFT JOIN users ON alerts.user_id = users.id WHERE alerts.id = ?').get(req.params.id);
  if (!row) return res.status(404).json({ error: 'Not found' });
  res.json(mapRow_alerts(row));
});

app.post('/api/alerts', writeLimiter, (req, res) => {
  try {
    const { monitor_id, type, target, enabled, created_at } = req.body;

    const user_id = req.user ? req.user.id : req.body.user_id;
    const info = db.prepare(
      'INSERT INTO alerts (monitor_id, user_id, type, target, enabled, created_at) VALUES (?, ?, ?, ?, ?, ?)'
    ).run(monitor_id, user_id, type, target, enabled, created_at);
    const created = db.prepare('SELECT alerts.id, alerts.monitor_id, alerts.user_id, alerts.type, alerts.target, alerts.enabled, alerts.created_at, monitors.id AS __monitor_id_id, monitors.name AS __monitor_id_name, monitors.url AS __monitor_id_url, monitors.type AS __monitor_id_type, monitors.interval_seconds AS __monitor_id_interval_seconds, monitors.status AS __monitor_id_status, monitors.last_check AS __monitor_id_last_check, monitors.avg_response_ms AS __monitor_id_avg_response_ms, monitors.uptime_30d AS __monitor_id_uptime_30d, monitors.user_id AS __monitor_id_user_id, users.id AS __user_id_id, users.email AS __user_id_email, users.org_name AS __user_id_org_name, users.plan AS __user_id_plan FROM alerts LEFT JOIN monitors ON alerts.monitor_id = monitors.id LEFT JOIN users ON alerts.user_id = users.id WHERE alerts.id = ?').get(info.lastInsertRowid);
    
    res.status(201).json(mapRow_alerts(created));
  } catch (e) {
    res.status(400).json({ error: e.message });
  }
});

app.put('/api/alerts/:id', writeLimiter, (req, res) => {
  try {
  const validCols = new Set(["monitor_id","user_id","type","target","enabled","created_at"]);
  const fields = Object.keys(req.body).filter(k => k !== 'id' && validCols.has(k));
  if (!fields.length) return res.status(400).json({ error: 'No valid fields to update' });
  const sets = fields.map(f => f + ' = ?').join(', ');
  const vals = fields.map(f => req.body[f]);
  vals.push(req.params.id);
  const info = db.prepare('UPDATE alerts SET ' + sets + ' WHERE id = ?').run(...vals);
  if (!info.changes) return res.status(404).json({ error: 'Not found' });
  res.json(db.prepare('SELECT * FROM alerts WHERE id = ?').get(req.params.id));
  } catch (e) {
    res.status(400).json({ error: e.message });
  }
});

app.delete('/api/alerts/:id', writeLimiter, (req, res) => {
  const info = db.prepare('DELETE FROM alerts WHERE id = ?').run(req.params.id);
  if (!info.changes) return res.status(404).json({ error: 'Not found' });
  res.json({ deleted: true });
});

// ── checks CRUD ──────────────────────────────────────

function mapRow_checks(row) {
    const r = { ...row };
    r.monitor_id = row.__monitor_id_id ? { id: row.__monitor_id_id, name: row.__monitor_id_name, url: row.__monitor_id_url, type: row.__monitor_id_type, interval_seconds: row.__monitor_id_interval_seconds, status: row.__monitor_id_status, last_check: row.__monitor_id_last_check, avg_response_ms: row.__monitor_id_avg_response_ms, uptime_30d: row.__monitor_id_uptime_30d, user_id: row.__monitor_id_user_id } : null;
    Object.keys(r).forEach(k => { if (k.startsWith('__')) delete r[k]; });
    return r;
  }
app.get('/api/checks', (req, res) => {
  // ── Filtering & Search ──
  const validColumns = new Set(["monitor_id","status","response_ms","status_code","error_msg","created_at"]);
  const textColumns = ["status","error_msg"];
  const filters = [];
  const params = [];
  for (const [key, value] of Object.entries(req.query)) {
    if (key === 'page' || key === 'limit' || key === 'search') continue;
    if (validColumns.has(key)) {
      filters.push(key + ' = ?');
      params.push(value);
    }
  }
  if (req.query.search && textColumns.length > 0) {
    filters.push('(' + textColumns.map(c => c + ' LIKE ?').join(' OR ') + ')');
    textColumns.forEach(() => params.push('%' + req.query.search + '%'));
  }
  const where = filters.length > 0 ? ' WHERE ' + filters.join(' AND ') : '';

  // ── Pagination (opt-in: only when ?page= or ?limit= is provided) ──
  if (req.query.page || req.query.limit) {
    const page = Math.max(1, parseInt(req.query.page) || 1);
    const limit = Math.min(100, Math.max(1, parseInt(req.query.limit) || 20));
    const offset = (page - 1) * limit;
    const total = db.prepare('SELECT COUNT(*) as count FROM checks' + where).get(...params).count;
    const rows = db.prepare('SELECT * FROM checks' + where + ' LIMIT ? OFFSET ?').all(...params, limit, offset).map(mapRow_checks);
    return res.json({ data: rows, pagination: { page, limit, total, pages: Math.ceil(total / limit) } });
  }

  // ── Default: return plain array (backwards-compatible) ──
  const rows = db.prepare('SELECT * FROM checks' + where).all(...params).map(mapRow_checks);
  res.json(rows);
});

app.get('/api/checks/:id', (req, res) => {
  const row = db.prepare('SELECT checks.id, checks.monitor_id, checks.status, checks.response_ms, checks.status_code, checks.error_msg, checks.created_at, monitors.id AS __monitor_id_id, monitors.name AS __monitor_id_name, monitors.url AS __monitor_id_url, monitors.type AS __monitor_id_type, monitors.interval_seconds AS __monitor_id_interval_seconds, monitors.status AS __monitor_id_status, monitors.last_check AS __monitor_id_last_check, monitors.avg_response_ms AS __monitor_id_avg_response_ms, monitors.uptime_30d AS __monitor_id_uptime_30d, monitors.user_id AS __monitor_id_user_id FROM checks LEFT JOIN monitors ON checks.monitor_id = monitors.id WHERE checks.id = ?').get(req.params.id);
  if (!row) return res.status(404).json({ error: 'Not found' });
  res.json(mapRow_checks(row));
});

app.post('/api/checks', writeLimiter, (req, res) => {
  try {
    const { monitor_id, status, response_ms, status_code, error_msg, created_at } = req.body;

    const info = db.prepare(
      'INSERT INTO checks (monitor_id, status, response_ms, status_code, error_msg, created_at) VALUES (?, ?, ?, ?, ?, ?)'
    ).run(monitor_id, status, response_ms, status_code, error_msg, created_at);
    const created = db.prepare('SELECT checks.id, checks.monitor_id, checks.status, checks.response_ms, checks.status_code, checks.error_msg, checks.created_at, monitors.id AS __monitor_id_id, monitors.name AS __monitor_id_name, monitors.url AS __monitor_id_url, monitors.type AS __monitor_id_type, monitors.interval_seconds AS __monitor_id_interval_seconds, monitors.status AS __monitor_id_status, monitors.last_check AS __monitor_id_last_check, monitors.avg_response_ms AS __monitor_id_avg_response_ms, monitors.uptime_30d AS __monitor_id_uptime_30d, monitors.user_id AS __monitor_id_user_id FROM checks LEFT JOIN monitors ON checks.monitor_id = monitors.id WHERE checks.id = ?').get(info.lastInsertRowid);
    
    res.status(201).json(mapRow_checks(created));
  } catch (e) {
    res.status(400).json({ error: e.message });
  }
});

app.put('/api/checks/:id', writeLimiter, (req, res) => {
  try {
  const validCols = new Set(["monitor_id","status","response_ms","status_code","error_msg","created_at"]);
  const fields = Object.keys(req.body).filter(k => k !== 'id' && validCols.has(k));
  if (!fields.length) return res.status(400).json({ error: 'No valid fields to update' });
  const sets = fields.map(f => f + ' = ?').join(', ');
  const vals = fields.map(f => req.body[f]);
  vals.push(req.params.id);
  const info = db.prepare('UPDATE checks SET ' + sets + ' WHERE id = ?').run(...vals);
  if (!info.changes) return res.status(404).json({ error: 'Not found' });
  res.json(db.prepare('SELECT * FROM checks WHERE id = ?').get(req.params.id));
  } catch (e) {
    res.status(400).json({ error: e.message });
  }
});

app.delete('/api/checks/:id', writeLimiter, (req, res) => {
  const info = db.prepare('DELETE FROM checks WHERE id = ?').run(req.params.id);
  if (!info.changes) return res.status(404).json({ error: 'Not found' });
  res.json({ deleted: true });
});

// ── incidents CRUD ──────────────────────────────────────

function mapRow_incidents(row) {
    const r = { ...row };
    r.user_id = row.__user_id_id ? { id: row.__user_id_id, email: row.__user_id_email, org_name: row.__user_id_org_name, plan: row.__user_id_plan } : null;
    Object.keys(r).forEach(k => { if (k.startsWith('__')) delete r[k]; });
    return r;
  }
app.get('/api/incidents', (req, res) => {
  // ── Filtering & Search ──
  const validColumns = new Set(["title","status","message","resolved_at","user_id"]);
  const textColumns = ["title","status","message","resolved_at"];
  const filters = [];
  const params = [];
  for (const [key, value] of Object.entries(req.query)) {
    if (key === 'page' || key === 'limit' || key === 'search') continue;
    if (validColumns.has(key)) {
      filters.push(key + ' = ?');
      params.push(value);
    }
  }
  if (req.query.search && textColumns.length > 0) {
    filters.push('(' + textColumns.map(c => c + ' LIKE ?').join(' OR ') + ')');
    textColumns.forEach(() => params.push('%' + req.query.search + '%'));
  }
  const where = filters.length > 0 ? ' WHERE ' + filters.join(' AND ') : '';

  // ── Pagination (opt-in: only when ?page= or ?limit= is provided) ──
  if (req.query.page || req.query.limit) {
    const page = Math.max(1, parseInt(req.query.page) || 1);
    const limit = Math.min(100, Math.max(1, parseInt(req.query.limit) || 20));
    const offset = (page - 1) * limit;
    const total = db.prepare('SELECT COUNT(*) as count FROM incidents' + where).get(...params).count;
    const rows = db.prepare('SELECT * FROM incidents' + where + ' LIMIT ? OFFSET ?').all(...params, limit, offset).map(mapRow_incidents);
    return res.json({ data: rows, pagination: { page, limit, total, pages: Math.ceil(total / limit) } });
  }

  // ── Default: return plain array (backwards-compatible) ──
  const rows = db.prepare('SELECT * FROM incidents' + where).all(...params).map(mapRow_incidents);
  res.json(rows);
});

app.get('/api/incidents/:id', (req, res) => {
  const row = db.prepare('SELECT incidents.id, incidents.title, incidents.status, incidents.message, incidents.resolved_at, incidents.user_id, users.id AS __user_id_id, users.email AS __user_id_email, users.org_name AS __user_id_org_name, users.plan AS __user_id_plan FROM incidents LEFT JOIN users ON incidents.user_id = users.id WHERE incidents.id = ?').get(req.params.id);
  if (!row) return res.status(404).json({ error: 'Not found' });
  res.json(mapRow_incidents(row));
});

app.post('/api/incidents', writeLimiter, (req, res) => {
  try {
    if (!req.body.title && req.body.title !== 0) return res.status(400).json({ error: 'title is required' });
    const { title, status, message, resolved_at } = req.body;

    const user_id = req.user ? req.user.id : req.body.user_id;
    const info = db.prepare(
      'INSERT INTO incidents (title, status, message, resolved_at, user_id) VALUES (?, ?, ?, ?, ?)'
    ).run(title, status, message, resolved_at, user_id);
    const created = db.prepare('SELECT incidents.id, incidents.title, incidents.status, incidents.message, incidents.resolved_at, incidents.user_id, users.id AS __user_id_id, users.email AS __user_id_email, users.org_name AS __user_id_org_name, users.plan AS __user_id_plan FROM incidents LEFT JOIN users ON incidents.user_id = users.id WHERE incidents.id = ?').get(info.lastInsertRowid);
    
    res.status(201).json(mapRow_incidents(created));
  } catch (e) {
    res.status(400).json({ error: e.message });
  }
});

app.put('/api/incidents/:id', writeLimiter, (req, res) => {
  try {
  const validCols = new Set(["title","status","message","resolved_at","user_id"]);
  const fields = Object.keys(req.body).filter(k => k !== 'id' && validCols.has(k));
  if (!fields.length) return res.status(400).json({ error: 'No valid fields to update' });
  const sets = fields.map(f => f + ' = ?').join(', ');
  const vals = fields.map(f => req.body[f]);
  vals.push(req.params.id);
  const info = db.prepare('UPDATE incidents SET ' + sets + ' WHERE id = ?').run(...vals);
  if (!info.changes) return res.status(404).json({ error: 'Not found' });
  res.json(db.prepare('SELECT * FROM incidents WHERE id = ?').get(req.params.id));
  } catch (e) {
    res.status(400).json({ error: e.message });
  }
});

app.delete('/api/incidents/:id', writeLimiter, (req, res) => {
  const deleteAll = db.transaction(() => {
    db.pragma('defer_foreign_keys = ON');
    db.prepare('DELETE FROM incident_updates WHERE incident_id = ?').run(req.params.id);
    db.prepare('DELETE FROM incidents WHERE id = ?').run(req.params.id);
  });
  deleteAll();
  res.json({ deleted: true });

});

// ── incident_updates CRUD ──────────────────────────────────────

function mapRow_incident_updates(row) {
    const r = { ...row };
    r.incident_id = row.__incident_id_id ? { id: row.__incident_id_id, title: row.__incident_id_title, status: row.__incident_id_status, message: row.__incident_id_message, resolved_at: row.__incident_id_resolved_at, user_id: row.__incident_id_user_id } : null;
    Object.keys(r).forEach(k => { if (k.startsWith('__')) delete r[k]; });
    return r;
  }
app.get('/api/incident_updates', (req, res) => {
  // ── Filtering & Search ──
  const validColumns = new Set(["incident_id","status","message"]);
  const textColumns = ["status","message"];
  const filters = [];
  const params = [];
  for (const [key, value] of Object.entries(req.query)) {
    if (key === 'page' || key === 'limit' || key === 'search') continue;
    if (validColumns.has(key)) {
      filters.push(key + ' = ?');
      params.push(value);
    }
  }
  if (req.query.search && textColumns.length > 0) {
    filters.push('(' + textColumns.map(c => c + ' LIKE ?').join(' OR ') + ')');
    textColumns.forEach(() => params.push('%' + req.query.search + '%'));
  }
  const where = filters.length > 0 ? ' WHERE ' + filters.join(' AND ') : '';

  // ── Pagination (opt-in: only when ?page= or ?limit= is provided) ──
  if (req.query.page || req.query.limit) {
    const page = Math.max(1, parseInt(req.query.page) || 1);
    const limit = Math.min(100, Math.max(1, parseInt(req.query.limit) || 20));
    const offset = (page - 1) * limit;
    const total = db.prepare('SELECT COUNT(*) as count FROM incident_updates' + where).get(...params).count;
    const rows = db.prepare('SELECT * FROM incident_updates' + where + ' LIMIT ? OFFSET ?').all(...params, limit, offset).map(mapRow_incident_updates);
    return res.json({ data: rows, pagination: { page, limit, total, pages: Math.ceil(total / limit) } });
  }

  // ── Default: return plain array (backwards-compatible) ──
  const rows = db.prepare('SELECT * FROM incident_updates' + where).all(...params).map(mapRow_incident_updates);
  res.json(rows);
});

app.get('/api/incident_updates/:id', (req, res) => {
  const row = db.prepare('SELECT incident_updates.id, incident_updates.incident_id, incident_updates.status, incident_updates.message, incidents.id AS __incident_id_id, incidents.title AS __incident_id_title, incidents.status AS __incident_id_status, incidents.message AS __incident_id_message, incidents.resolved_at AS __incident_id_resolved_at, incidents.user_id AS __incident_id_user_id FROM incident_updates LEFT JOIN incidents ON incident_updates.incident_id = incidents.id WHERE incident_updates.id = ?').get(req.params.id);
  if (!row) return res.status(404).json({ error: 'Not found' });
  res.json(mapRow_incident_updates(row));
});

app.post('/api/incident_updates', writeLimiter, (req, res) => {
  try {
    if (!req.body.message && req.body.message !== 0) return res.status(400).json({ error: 'message is required' });
    const { incident_id, status, message } = req.body;

    const info = db.prepare(
      'INSERT INTO incident_updates (incident_id, status, message) VALUES (?, ?, ?)'
    ).run(incident_id, status, message);
    const created = db.prepare('SELECT incident_updates.id, incident_updates.incident_id, incident_updates.status, incident_updates.message, incidents.id AS __incident_id_id, incidents.title AS __incident_id_title, incidents.status AS __incident_id_status, incidents.message AS __incident_id_message, incidents.resolved_at AS __incident_id_resolved_at, incidents.user_id AS __incident_id_user_id FROM incident_updates LEFT JOIN incidents ON incident_updates.incident_id = incidents.id WHERE incident_updates.id = ?').get(info.lastInsertRowid);
    
    res.status(201).json(mapRow_incident_updates(created));
  } catch (e) {
    res.status(400).json({ error: e.message });
  }
});

app.put('/api/incident_updates/:id', writeLimiter, (req, res) => {
  try {
  const validCols = new Set(["incident_id","status","message"]);
  const fields = Object.keys(req.body).filter(k => k !== 'id' && validCols.has(k));
  if (!fields.length) return res.status(400).json({ error: 'No valid fields to update' });
  const sets = fields.map(f => f + ' = ?').join(', ');
  const vals = fields.map(f => req.body[f]);
  vals.push(req.params.id);
  const info = db.prepare('UPDATE incident_updates SET ' + sets + ' WHERE id = ?').run(...vals);
  if (!info.changes) return res.status(404).json({ error: 'Not found' });
  res.json(db.prepare('SELECT * FROM incident_updates WHERE id = ?').get(req.params.id));
  } catch (e) {
    res.status(400).json({ error: e.message });
  }
});

app.delete('/api/incident_updates/:id', writeLimiter, (req, res) => {
  const info = db.prepare('DELETE FROM incident_updates WHERE id = ?').run(req.params.id);
  if (!info.changes) return res.status(404).json({ error: 'Not found' });
  res.json({ deleted: true });
});

// ── status_pages CRUD ──────────────────────────────────────

function mapRow_status_pages(row) {
    const r = { ...row };
    r.user_id = row.__user_id_id ? { id: row.__user_id_id, email: row.__user_id_email, org_name: row.__user_id_org_name, plan: row.__user_id_plan } : null;
    Object.keys(r).forEach(k => { if (k.startsWith('__')) delete r[k]; });
    return r;
  }
app.get('/api/status_pages', (req, res) => {
  // ── Filtering & Search ──
  const validColumns = new Set(["slug","name","monitor_ids","custom_domain","user_id"]);
  const textColumns = ["slug","name","monitor_ids","custom_domain"];
  const filters = [];
  const params = [];
  for (const [key, value] of Object.entries(req.query)) {
    if (key === 'page' || key === 'limit' || key === 'search') continue;
    if (validColumns.has(key)) {
      filters.push(key + ' = ?');
      params.push(value);
    }
  }
  if (req.query.search && textColumns.length > 0) {
    filters.push('(' + textColumns.map(c => c + ' LIKE ?').join(' OR ') + ')');
    textColumns.forEach(() => params.push('%' + req.query.search + '%'));
  }
  const where = filters.length > 0 ? ' WHERE ' + filters.join(' AND ') : '';

  // ── Pagination (opt-in: only when ?page= or ?limit= is provided) ──
  if (req.query.page || req.query.limit) {
    const page = Math.max(1, parseInt(req.query.page) || 1);
    const limit = Math.min(100, Math.max(1, parseInt(req.query.limit) || 20));
    const offset = (page - 1) * limit;
    const total = db.prepare('SELECT COUNT(*) as count FROM status_pages' + where).get(...params).count;
    const rows = db.prepare('SELECT * FROM status_pages' + where + ' LIMIT ? OFFSET ?').all(...params, limit, offset).map(mapRow_status_pages);
    return res.json({ data: rows, pagination: { page, limit, total, pages: Math.ceil(total / limit) } });
  }

  // ── Default: return plain array (backwards-compatible) ──
  const rows = db.prepare('SELECT * FROM status_pages' + where).all(...params).map(mapRow_status_pages);
  res.json(rows);
});

app.get('/api/status_pages/:id', (req, res) => {
  const row = db.prepare('SELECT status_pages.id, status_pages.slug, status_pages.name, status_pages.monitor_ids, status_pages.custom_domain, status_pages.user_id, users.id AS __user_id_id, users.email AS __user_id_email, users.org_name AS __user_id_org_name, users.plan AS __user_id_plan FROM status_pages LEFT JOIN users ON status_pages.user_id = users.id WHERE status_pages.id = ?').get(req.params.id);
  if (!row) return res.status(404).json({ error: 'Not found' });
  res.json(mapRow_status_pages(row));
});

app.post('/api/status_pages', writeLimiter, (req, res) => {
  try {
    if (!req.body.slug && req.body.slug !== 0) return res.status(400).json({ error: 'slug is required' });
    if (!req.body.name && req.body.name !== 0) return res.status(400).json({ error: 'name is required' });
    const { slug, name, monitor_ids, custom_domain } = req.body;

    const user_id = req.user ? req.user.id : req.body.user_id;
    const info = db.prepare(
      'INSERT INTO status_pages (slug, name, monitor_ids, custom_domain, user_id) VALUES (?, ?, ?, ?, ?)'
    ).run(slug, name, monitor_ids, custom_domain, user_id);
    const created = db.prepare('SELECT status_pages.id, status_pages.slug, status_pages.name, status_pages.monitor_ids, status_pages.custom_domain, status_pages.user_id, users.id AS __user_id_id, users.email AS __user_id_email, users.org_name AS __user_id_org_name, users.plan AS __user_id_plan FROM status_pages LEFT JOIN users ON status_pages.user_id = users.id WHERE status_pages.id = ?').get(info.lastInsertRowid);
    
    res.status(201).json(mapRow_status_pages(created));
  } catch (e) {
    res.status(400).json({ error: e.message });
  }
});

app.put('/api/status_pages/:id', writeLimiter, (req, res) => {
  try {
  const validCols = new Set(["slug","name","monitor_ids","custom_domain","user_id"]);
  const fields = Object.keys(req.body).filter(k => k !== 'id' && validCols.has(k));
  if (!fields.length) return res.status(400).json({ error: 'No valid fields to update' });
  const sets = fields.map(f => f + ' = ?').join(', ');
  const vals = fields.map(f => req.body[f]);
  vals.push(req.params.id);
  const info = db.prepare('UPDATE status_pages SET ' + sets + ' WHERE id = ?').run(...vals);
  if (!info.changes) return res.status(404).json({ error: 'Not found' });
  res.json(db.prepare('SELECT * FROM status_pages WHERE id = ?').get(req.params.id));
  } catch (e) {
    res.status(400).json({ error: e.message });
  }
});

app.delete('/api/status_pages/:id', writeLimiter, (req, res) => {
  const info = db.prepare('DELETE FROM status_pages WHERE id = ?').run(req.params.id);
  if (!info.changes) return res.status(404).json({ error: 'Not found' });
  res.json({ deleted: true });
});


app.get('/api/status-pages/:slug/public', (req, res) => {
  try {
    const row = db.prepare(`SELECT * FROM status_pages WHERE slug = ? LIMIT 1`).get(req.params.slug);
    if (!row) return res.status(404).json({ error: 'Not found' });
    res.json(row);
  } catch (e) {
    res.status(500).json({ error: e.message });
  }
});

app.get('/api/incidents/active', authMiddleware, (req, res) => {
  try {
    const rows = db.prepare(`SELECT * FROM incidents WHERE user_id = ? AND status != 'resolved' ORDER BY created_at DESC`).all(req.user.id);
    res.json(rows);
  } catch (e) {
    res.status(500).json({ error: e.message });
  }
});

app.get('/api/monitors/:id/checks', (req, res) => {
  try {
    const rows = db.prepare(`SELECT id, status, response_ms, status_code, error_msg, created_at FROM checks WHERE monitor_id = ? ORDER BY id DESC LIMIT 100`).all(req.params.id);
    res.json(rows);
  } catch (e) {
    res.status(500).json({ error: e.message });
  }
});

app.post('/api/monitors/:id/alerts', authMiddleware, (req, res) => {
  try {
    const info = db.prepare(`INSERT INTO alerts (monitor_id, user_id, type, target) VALUES (?, ?, ?, ?)`).run(req.params.id, req.user.id, req.body.type, req.body.target);
    res.status(201).json({ id: info.lastInsertRowid, ...req.body });
  } catch (e) {
    res.status(500).json({ error: e.message });
  }
});

app.get('/api/monitors/:id/alerts', authMiddleware, (req, res) => {
  try {
    const rows = db.prepare(`SELECT * FROM alerts WHERE monitor_id = ? AND user_id = ?`).all(req.params.id, req.user.id);
    res.json(rows);
  } catch (e) {
    res.status(500).json({ error: e.message });
  }
});

app.delete('/api/alerts/:id', authMiddleware, (req, res) => {
  try {
    const info = db.prepare(`DELETE FROM alerts WHERE id = ? AND user_id = ?`).run(req.params.id, req.user.id);
    res.json({ changes: info.changes });
  } catch (e) {
    res.status(500).json({ error: e.message });
  }
});


// ── Role guard middleware ────────────────────────────────────
function roleGuard(role) {
  return (req, res, next) => {
    if (!req.user) return res.status(401).json({ error: 'Authentication required' });
    const user = db.prepare('SELECT role FROM users WHERE id = ?').get(req.user.id);
    if (!user || user.role !== role) return res.status(403).json({ error: 'Insufficient permissions' });
    next();
  };
}

// ── Named Middleware ──────────────────────────────────────────


// ── Error handler ──────────────────────────────────────────────

app.use((err, req, res, next) => {
  console.error('Error:', err.message);
  res.status(500).json({ error: err.message });
});



// ── Static File Serving ─────────────────────────────────────────
const distDir = path.join(__dirname, '.');
app.use(express.static(distDir));

// ── Start ──────────────────────────────────────────────────────

const PORT = process.env.PORT || 3000;
const server = app.listen(PORT, () => console.log(`NyxCode server listening on :${PORT}`));

// ── Background Workers (every blocks) ─────────────────────────────────

// every 60s 'health-check'
const interval_health_check = setInterval(async () => {
  try {
    const rows = db.prepare("SELECT id, url FROM monitors WHERE COALESCE(status, 'unknown') != 'paused'").all();
    for (const row of rows) {
      const start = Date.now();
      try {
        const res = await fetch(row.url, { signal: AbortSignal.timeout(10000) });
        const ms = Date.now() - start;
        db.prepare("INSERT INTO checks (monitor_id, status, response_ms, status_code) VALUES (?, ?, ?, ?)").run(row.id, res.ok ? 'up' : 'down', ms, res.status);
        db.prepare("UPDATE monitors SET status = ?, last_check = datetime('now'), avg_response_ms = ? WHERE id = ?").run(res.ok ? 'up' : 'down', ms, row.id);
      } catch(fetchErr) {
        const ms = Date.now() - start;
        db.prepare("INSERT INTO checks (monitor_id, status, response_ms, error_msg) VALUES (?, 'down', ?, ?)").run(row.id, ms, fetchErr.message);
        db.prepare("UPDATE monitors SET status = 'down', last_check = datetime('now') WHERE id = ?").run(row.id);
      }
    }
  } catch(e) {
    console.error('[every:health_check]', e.message);
  }
}, 60000);

// every 1h 'cleanup-old-checks'
const interval_cleanup_old_checks = setInterval(async () => {
  try {
    db.prepare("DELETE FROM checks WHERE created_at < datetime('now', '-30 days')").run();
  } catch(e) {
    console.error('[every:cleanup_old_checks]', e.message);
  }
}, 3600000);

process.on('SIGTERM', () => {
  clearInterval(interval_health_check);
  clearInterval(interval_cleanup_old_checks);
  server.close();
  process.exit(0);
});

process.on('SIGINT', () => {
  clearInterval(interval_health_check);
  clearInterval(interval_cleanup_old_checks);
  server.close();
  process.exit(0);
});

console.log('⏰ 2 background worker(s) started');


